server:
  port: 8080

spring:
  application:
    name: my-web-ide

  # ?????? ?? (?? ??? DB? H2 ??)
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # http://localhost:8080/h2-console ? DB ?? ??

  # ?? ??? ?? (??? ???? ??? ???? ? ??)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# ??? ?? (??? ?? ???? ???? ? ??)
ide:
  docker:
    host: tcp://localhost:2375  # ???/? ?? ?? ??
    workspace-path: ./temp-workspace # ??? ??? ??? ?? ??